### ISSUE TITLE
Make overriding `render` less common

### ISSUE THREAD

**Issue by domenic** [YuzuJS/WinningJS-todo#1]
We're overriding `render` in all of our components. This is awkward.

Ideas:
- Provide better hooks, e.g. for event binding. See [AddForm](https://github.com/NobleJS/WinningJS-todo/blob/883126318559ec19451d47425eb4e563a5b29ed4/lib/components/AddForm/index.js)
- Make the rendered element a public property, so it can be accessed without overriding and saving a reference. See [ListView](https://github.com/NobleJS/WinningJS-todo/blob/883126318559ec19451d47425eb4e563a5b29ed4/lib/components/ListView/index.js).
  - A variation of the public property idea, which preserves encapsulation better. Maybe `var privates = mixinComponent(this, options)`, then you can get access to e.g. `privates.element`, `privates.publish`, etc.?

**Comment by pbouzakis** [comment]
The new Presenter modules takes care of most of the use cases for where previously an override of render was necessary.  The method is now called process, and the presenter object exposes the element object directly after creation.  By using composition over inheritance we still get the benefits of encapsulation.

The only use-case left is when you need to do something w/ the element AFTER it has been processed.  So we could introduce a hook (maybe afterProcess, afterUIProcess, etc).  That would pretty much take care of anyone needed to override process.

Or we could be okay with this last scenario.

**Comment by domenic** [comment]
Yeah, I think this is good now. We can do

``` js
that.render = function () {
    presenter.process().then(function () {
        // ...
    });
};
```

to meet that use case.
